~inst.startFlop();
~inst.takeSnapshot();
~inst.showSnapshot();

~inst.crankThatSoulja();

~inst.norm();

~inst.wrinkle();

~inst.sputter();

~inst.drone();

~inst.cook();

~inst.funWithNorm();

~inst.freak();

~inst.bleepAbout();

~inst.subZipper();

~inst.subAndBlop();

~inst.transferBlang();

~inst.biter(0.5,220);

~inst.sayWow();
~inst.sayWow(10,3);

~inst.vasilate();

~inst.slurp(0.8);

~inst.climb();

~inst.humm();
~inst.humm(2, 0.06, 0.65);

~inst.currFunc

~inst.norm();
